const c=document.querySelector('#game'),x=c.getContext('2d'),score=document.querySelector('#score'),btn=document.querySelector('#start'),color=document.querySelector('#color');
const N=20,S=c.width/N;let snake,food,dir,next,timer,playing=false,paused=false,touch;
function reset(){snake=[{x:10,y:10},{x:9,y:10},{x:8,y:10}];dir=next={x:1,y:0};score.textContent=0;place();draw()}
function place(){do food={x:Math.floor(Math.random()*N),y:Math.floor(Math.random()*N)};while(snake.some(p=>p.x==food.x&&p.y==food.y))}
function start(){clearInterval(timer);reset();playing=true;paused=false;btn.textContent='다시 시작';timer=setInterval(step,105)}
function step(){if(paused)return;dir=next;let h={x:snake[0].x+dir.x,y:snake[0].y+dir.y};if(h.x<0||h.x>=N||h.y<0||h.y>=N||snake.some(p=>p.x==h.x&&p.y==h.y)){playing=false;clearInterval(timer);draw('GAME OVER');return}snake.unshift(h);if(h.x==food.x&&h.y==food.y){score.textContent=+score.textContent+10;place()}else snake.pop();draw()}
function draw(msg=''){x.fillStyle='#171d16';x.fillRect(0,0,c.width,c.height);x.fillStyle='#ff6b5e';x.beginPath();x.arc((food.x+.5)*S,(food.y+.5)*S,S*.3,0,7);x.fill();snake.forEach((p,i)=>{x.fillStyle=color.value+(i?'bb':'');x.beginPath();x.roundRect(p.x*S+2,p.y*S+2,S-4,S-4,6);x.fill()});if(msg||paused){x.fillStyle='#10130fdd';x.fillRect(0,190,480,100);x.fillStyle='#edf7e8';x.textAlign='center';x.font='700 30px system-ui';x.fillText(msg||'PAUSED',240,250)}}
function turn(dx,dy){if(!playing)return;if(dx===-dir.x&&dy===-dir.y){snake.reverse();dir=next={x:dx,y:dy};draw();return}next={x:dx,y:dy}}
addEventListener('keydown',e=>{let k=e.key.toLowerCase(),m={arrowup:[0,-1],w:[0,-1],arrowdown:[0,1],s:[0,1],arrowleft:[-1,0],a:[-1,0],arrowright:[1,0],d:[1,0]}[k];if(m){e.preventDefault();turn(...m)}if(e.code==='Space'&&playing){e.preventDefault();paused=!paused;draw()}});
c.addEventListener('pointerdown',e=>touch=[e.clientX,e.clientY]);c.addEventListener('pointerup',e=>{let dx=e.clientX-touch[0],dy=e.clientY-touch[1];Math.abs(dx)>Math.abs(dy)?turn(Math.sign(dx),0):turn(0,Math.sign(dy))});color.oninput=()=>{document.querySelector('.wrap').style.setProperty('--snake',color.value);draw()};btn.onclick=start;reset();
